[FE] review 수정
MultiProject23/React-Project pull request #66
Opened 2023-03-13 16:19 UTC by umtaemin1125

# 개요

#53

## 작업사항

- [x] 주석 제거
- [x] public/img/ReviewTest.jpg 파일 추가 및 json 파일 image 경로 수정
- [x] 카멜 표기법으로 수정
- [x] UI 수정
- [x] 필터링이 가능한 Nav 구현
- [x]  리뷰가 존재하지 않는 경우 출력문 출력

## 기타사항
[23/03/14]
- UI 
리뷰 컨테이너 : 폭 80% -> 60% 조정 / 배경색 white로 수정
리뷰 모달 : 이미지 크기 조정 / 프로필 이미지 삭제 / X버튼 size 조절
리뷰 목록 : 이미지 크기 조정 / 
- 기능
페이지네이션 구현
쿼리스트링 구현 (useNavigate, useLocation 사용)
모달 json 데이터 받아올 수 있게 구현
리뷰 작성 글 100자 이상 시 ... 으로 표시될 수 있게 구현

![review](https://user-images.githubusercontent.com/73513060/225377961-53e88b04-e699-4a1f-ab67-bb6a1e03147f.gif)

2023-03-14 00:17 UTC, KIMSEI1124 reviewed
정리하신거 확인했습니다.
추후 코드에는 주석이 없는 상태로 만들 예정 이라서 해야하는 작업중 하나 입니다!
필터링이 가능한 Nav는 현재 #63 해당 소스 코드를 확인하시면 구현을 해뒀는데 확인해보시면 좋을 것 같습니다.

2023-03-15 16:35 UTC, umtaemin1125 commented
[23/03/15]
- UI 수정
- 기능
필터링이 가능한 카테고리 Nav바 구현 (상품페이지와 동일한 카테고리)
리뷰가 존재하지 않는 경우 출력되는 페이지 구현

![review_category](https://user-images.githubusercontent.com/73513060/225376734-6d8bc658-81d3-43f1-90aa-5d2665d0db9c.gif)

2023-03-18 12:55 UTC, KIMSEI1124 reviewed
답변 해주시고! 이상 없으면 PR 허용 해드리겠습니다.

2023-03-18 12:55 UTC, KIMSEI1124 commented on src/components/Review/ReviewModal/index.jsx
> +                <S.Review_Modal_ImagePrd src={data?.image}></S.Review_Modal_ImagePrd>
혹시 `data?image` 에서 `?` 의 의미는 무엇일까요?
궁금해서 질문드립니다.

2023-03-18 12:55 UTC, KIMSEI1124 commented on src/components/Review/ReviewPagenation/index.styled.js
> +// }
주석 처리를 하셨는데 30-33번째 행과 연관이 있는건가요?

2023-03-18 12:55 UTC, KIMSEI1124 commented on src/components/Review/index.jsx
> +};
추후 이 내용은 Import 해서 사용하시면 좋을 것 같습니다. 추후 내용을 추가하도록 하죠 일단은 OK입니다.

2023-03-18 12:59 UTC, KIMSEI1124 reviewed
.

2023-03-19 05:06 UTC, umtaemin1125 commented on src/components/Review/ReviewModal/index.jsx
> +                <S.Review_Modal_ImagePrd src={data?.image}></S.Review_Modal_ImagePrd>
모달에 리뷰데이터 받아오는 코드 작성중에 이미지를 자꾸 못 받아와서 구글링으로 **옵셔널 체이닝** 문법이라고 객체가 null이나 undefined일 경우에 에러를 발생시키지 않고, 접근할 수 있게 하는 문법을 사용하여 테스트 했습니다. 현재는 해당 문법을 사용하지 않아도 오류가 발생하지 않습니다. 수정이 필요하시면 수정하겠습니다.

2023-03-19 05:08 UTC, umtaemin1125 commented on src/components/Review/ReviewPagenation/index.styled.js
> +// }
해당 부분은 페이지네이션 스타일 테스트하면서 주석처리해놨는데 미처 확인 못하고 못 지운거 같습니다. 해당 주석 지우겠습니다.

2023-03-19 05:08 UTC, umtaemin1125 commented on src/components/Review/index.jsx
> +};
네 알겠습니다 추후 import하여 처리하도록 하겠습니다.

2023-03-19 05:36 UTC, KIMSEI1124 commented on src/components/Review/ReviewModal/index.jsx
> +                <S.Review_Modal_ImagePrd src={data?.image}></S.Review_Modal_ImagePrd>
오 신기한 문법이네요 추후 문제가 생기면 수정하는 거로 하고 일단은 그대로 진행하죠

2023-03-19 05:36 UTC, KIMSEI1124 commented on src/components/Review/ReviewPagenation/index.styled.js
> +// }
확인했습니다~

2023-03-20 04:09 UTC, KIMSEI1124 requested changes
최종 확인 했고 PR 진행하겠습니다.

2023-03-20 04:09 UTC, KIMSEI1124 approved these changes
PR 진행하겠습니다!.

2023-03-20 04:10 UTC, merged